### ISSUE TITLE
出现白屏现象

### ISSUE THREAD

**Issue by ShiyuWang07** [RyanEdo/mini-metro-web#10]
选择了从一个站开始一条新线，点击了要添加的第二个站之后线未能显示出来，整个页面也白屏了，创作的图也未能保存下来。点击了恢复数据也恢复的是默认提瓦特的图而不是我创作的图。

**Comment by ShiyuWang07** [comment]
另外创作的地图有没有可能以网页的形式保存？

**Comment by RyanEdo** [comment]
导出恢复也不行吗？
创作地图用网页保存是指保存成HTML吗？暂时还没有考虑做成html
