### ISSUE TITLE
关于mini-metro-web的一些建议

### ISSUE THREAD

**Issue by liangfukang** [RyanEdo/mini-metro-web#12]
1.在一条线路上添加站点只能从终点站添加而不能从始发站添加，希望两个站都能添加
2.能不能添加这个图标用于表示换乘站
![微信图片_20240731205327](https://github.com/user-attachments/assets/bc6ca45c-3a38-4428-b8c3-6339cd559188)
3.在编辑线路图时能不能自己导入一张地图在自己导入的基础上编辑线路图
![微信图片_20240731205300](https://github.com/user-attachments/assets/13c915b4-c092-420d-9737-b8890d7e00bf)
4.如果是环线这个突出的能不能去掉
![image](https://github.com/user-attachments/assets/686e4b10-a63a-4fe2-8c21-e45e53249f39)

**Comment by RyanEdo** [comment]
感谢你的issue。
1. 可以从任意一个站点开始添加，只需要点击菜单，选择线路分组下的插入站点，这个时候再点击线路，就会发现所有的站点上都有加号，点这个加号就可以从选中站点处添加。
![Screenshot_2024-07-31-21-08-42-312_com.android.chrome.jpg](https://github.com/user-attachments/assets/0d2a57db-e9e7-483f-a4c7-a36f7f7dbabb)

2. 背景图片会在下个版本加入

3. 换乘站的样式和环线的样式目前都是和迷你地铁这个游戏保持一致的，后续可能会增加样式或者控制把手显示的选项。
