### ISSUE TITLE
Please add English 

### ISSUE THREAD

**Issue by R-iscool** [RyanEdo/mini-metro-web#23]
I really like this game but I don't understand Chinese. Hence English as a language would be appreciated a lot. I would be grateful if you could release it soon.

**Comment by RyanEdo** [comment]
Sure! English will be added in the next version.

**Comment by R-iscool** [comment]
Okay tysm! If possible please let me know the date of the next release

**Comment by RyanEdo** [comment]
i'm not sure the exactly time for next release. i'll update asap

**Comment by R-iscool** [comment]
Okay thanks!

**Comment by RyanEdo** [comment]
English added

**Comment by R-iscool** [comment]
Thank you so much!
