### ISSUE TITLE
非常好的项目

### ISSUE THREAD

**Issue by yilianxin** [RyanEdo/mini-metro-web#6]
感谢作者，非常好的项目。
提个建议，是否可以上传图片，然后以图片为背景，在背景上创建节点。

**Comment by RyanEdo** [comment]
谢谢你的建议～

将会在下个版本增加背景图功能。

**Comment by yilianxin** [comment]
另外可以考虑增加工具栏功能。目前虽然功能已经基本完备了，但是操作还是有多少不方便的地方。
例如想要添加站点就必须标题-->添加站点 或者插入站点，其他类似。
可以考虑在屏幕顶部、底部、左右侧这些地方增加一个工具栏。
里面可以有增加站点，删除站点，站点连线，站点删线，导出等等。
另外站点连线的颜色修改建议直接放在第一个首站点上，即使有交叉站点，也不会影响功能

**Comment by RyanEdo** [comment]
工具栏的地方以后会考虑重新设计一下，尽量兼顾美观和实用性。

线路颜色现在是在线路卡片二级菜单里，我感觉这个功能应该不会频繁使用，放在站点卡片里反而有点奇怪。这个部分我没太明白为什么要放在首站里来修改。

**Comment by yilianxin** [comment]
线路颜色只是随意的一个想法。
我的想法是在整体上做减法，将所有功能直观化，将二级菜单的功能提出来。颜色调整也不一定非要放在首站，放在首站的想法比较随意，只是考虑可以做一个约束，不要随意点击连线然后就可以通过二级菜单修改颜色。
另外执行npm start后报错，报错信息如下，大佬看看如何解决。
Compiled with problems:
×
ERROR in ./src/WelcomeTour/WelcomeTour.tsx 7:0-45
Module not found: Error: Cannot find file: 'goto.tsx' does not match the corresponding name on disk: '.\src\Resource\Icon\GoTo.tsx'.
ERROR in ./src/WelcomeTour/WelcomeTour.tsx 11:0-36
Module not found: Error: Cannot find file: 'Driver.ts' does not match the corresponding name on disk: '.\src\WelcomeTour\driver.ts'.
ERROR in src/WelcomeTour/WelcomeTour.tsx:11:22
TS1261: Already included file name 'C:/Tools/mini-metro-web/src/Resource/Icon/goto.tsx' differs from file name 'C:/Tools/mini-metro-web/src/Resource/Icon/GoTo.tsx' only in casing.
  The file is in the program because:
    Imported via "../Resource/Icon/goto" from file 'C:/Tools/mini-metro-web/src/WelcomeTour/WelcomeTour.tsx'
    Root file specified for compilation
     9 | import "./WelcomeTour.scss";
    10 | import Infinity from "../Resource/Icon/infinity";
  > 11 | import GoToIcon from "../Resource/Icon/goto";
       |                      ^^^^^^^^^^^^^^^^^^^^^^^
    12 | import { hightLights } from "./HightLights";
    13 | import classNames from "classnames";
    14 | import { onWheelX } from "../Common/util";
ERROR in src/WelcomeTour/WelcomeTour.tsx:15:26
TS1261: Already included file name 'C:/Tools/mini-metro-web/src/WelcomeTour/Driver.ts' differs from file name 'C:/Tools/mini-metro-web/src/WelcomeTour/driver.ts' only in casing.
  The file is in the program because:
    Imported via "./Driver" from file 'C:/Tools/mini-metro-web/src/WelcomeTour/WelcomeTour.tsx'
    Root file specified for compilation
    13 | import classNames from "classnames";
    14 | import { onWheelX } from "../Common/util";
  > 15 | import { showTour } from "./Driver";
       |                          ^^^^^^^^^^
    16 | import { ShowTourProps, UserDataType } from "../Data/UserData";
    17 | import FinishedIcon from "../Resource/Icon/finished";
    18 | import QRCode from "qrcode";

**Comment by RyanEdo** [comment]
好的，等我之后有空再好好想想设计的部分。

这个问题是我本地文件改名（只改了大小写）被git直接忽略了，
导致本地和GitHub代码不一致导致的。
我本地配置`git config core.ignorecase false`就好了，我修改一下。
