### ISSUE TITLE
关于站点形状的一点建议

### ISSUE THREAD

**Issue by suntrise** [RyanEdo/mini-metro-web#7]
能否根据 Mini Metro 的设定增设站点：
![image](https://github.com/user-attachments/assets/88e29e01-ea20-4da9-88f8-4ba397c7420e)

并且可以在鼠标悬停在站点符号上时显示提示，如圆形显示“居住区”，三角形显示“工作区”，等等

**Comment by RyanEdo** [comment]
好的，迷你地铁游戏内内置的形状后续都会添加。

鼠标悬停显示“居住区”和“工作区”这个我要再考虑一下，
我的想法是现在已经有站点名了，再悬停显示形状所代表的区域感觉必要性不大，而且不同的用户可能对形状的定义不一样。
